name: base_core
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # ==== package core ========
  local_services:
    path: packages_core/local_services
  helper_utils:
    path: packages_core/helper_utils

  intl: ^0.19.0
  bot_toast: ^4.1.3
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  get_it: ^8.0.3
  event_bus: ^2.0.1
  chucker_flutter: ^1.8.3
  easy_localization: ^3.0.7
  cached_network_image: ^3.4.1
  loader_overlay: ^5.0.0
  flutter_gen: ^5.8.0
  flutter_lints: ^5.0.0
  json_annotation: ^4.9.0
  toastification: ^2.3.0
  mime: ^2.0.0
  path: ^1.9.0
  flutter_svg: ^2.0.16
  flutter_flavorizr: ^2.2.3
  collection: ^1.19.0
  flutter_dotenv: ^5.2.1
  go_router: ^7.0.0
  go_transitions: ^0.7.1
# ===========================



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: any


flutter:
  uses-material-design: true
  generate: true

  assets:
    - environments/.env
    - assets/app/
    - assets/i18n/

#  fonts:
#    - family: Fira_Sans
#      fonts:
#        - asset: assets/font/Fira_Sans/FiraSans-Medium.ttf