name: base_core
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ==== package core ========
  core_utils:
    path: ../core_utils

  intl: ^0.20.2
  bot_toast: ^4.1.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  event_bus: ^2.0.1
  chucker_flutter: ^1.8.5
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1
  loader_overlay: ^5.0.0
  flutter_gen: ^5.10.0
  flutter_lints: ^5.0.0
  json_annotation: ^4.9.0
  toastification: ^3.0.2
  mime: ^2.0.0
  path: ^1.9.1
  flutter_svg: ^2.1.0
  flutter_flavorizr: ^2.4.1
  collection: ^1.19.1
  flutter_dotenv: ^5.2.1
  auto_route: ^10.0.1
# ===========================


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: any

dependency_overrides:
  intl: ^0.20.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - environments/.env
    - environments/develop.env
    - assets/app/
    - assets/i18n/

#  fonts:
#    - family: Fira_Sans
#      fonts:
#        - asset: assets/font/Fira_Sans/FiraSans-Medium.ttf