name: local_services
description: Local Services
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.3
  mocktail: ^1.0.4
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
