name: helper_utils
description: Function helper
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any
  http: any
  intl: any
  mime: any
  path: any
  timezone: any
  equatable: any
  file_picker: any
  flutter_bloc: any
  url_launcher: any
  path_provider: any
  flutter_animate: any
  shared_preferences: any
  flutter_secure_storage: any

dev_dependencies:
  flutter_test:
    sdk: flutter
