name: helper_utils
description: Function helper
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  dio: any
  intl: any
  mime: any
  path: any
  file_picker: any
  path_provider: any
  url_launcher: any
  flutter_bloc: any
  equatable: any
  timezone: any
  flutter_animate: any
  http: any
  flutter_secure_storage: ^9.2.3
  mocktail: ^1.0.4
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
